runtime: python39

env_variables:
  # IMPORTANT: Set these in GCP Console -> App Engine -> Settings -> Environment Variables
  # Do NOT commit sensitive values here. Use GCP Secret Manager for production.
  # DATABASE_URL: "postgresql://postgres:rpLvgOls4fFSUKb3@db.hjhqgmkltsfscgfehipf.supabase.co:5432/postgres"
  # SECRET_KEY: "your-secret-key-here"
  # LLM_API_KEY: "your-llm-api-key-here"
  # LLM_PROVIDER: "gemini"
  # LLM_MODEL: "gemini-2.0-flash"

automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.6

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

handlers:
- url: /static
  static_dir: src/static

- url: /.*
  script: auto

entrypoint: gunicorn -w 2 --threads 2 --bind 0.0.0.0:8080 --timeout 120 application:application

